config/routes.rb
Rails.application.routes.draw do

  root 'rss_feeds#index'
	
	
	get '/login' => 'sessions#new'
	post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
	get '/signup' => 'users#new'
	post '/users' => 'users#create'
	
	resources :users, only: [:edit, :update]
	resources :rss_feeds, only: [:index] do
		collection do 
			get "recent"
		end
		resources :comments, only: [:index, :create] do
	    resources :comments, only: [:create]
	  end
	end
	get '/events', to: 'rss_feeds#events'
	
	
	

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	
	belongs_to :rss_feed, counter_cache: true
	has_many :replies, class_name: "Comment", foreign_key: "parent_id"
	
	validates :body, presence: true
	validates :rss_feed, presence: true
	
end

app/models/rss_feed.rb
class RssFeed < ActiveRecord::Base
		
	has_many :comments, -> { where parent_id: nil } 
		
	class << self
		def populate_from_xml(content)
			xml_feeds = Nokogiri.XML(content)
			rss_feed_ids = []
			xml_feeds.xpath("//item").each do |item|
				rss_feed_ids << RssFeed.create(title: item.search('title').text, summary: item.search('description').text.gsub(/<[^>]*>/,''), published_at: item.search('pubDate').text.to_datetime, url: item.search('link').text).id
			end
			notify_rss_feed_created(rss_feed_ids.join(','))
		end
	
		def notify_rss_feed_creation
			listen
			#Wait for notification or timeout and return nil
			RssFeed.connection.raw_connection.wait_for_notify(NOTIFY_TIMEOUT) do |event, pid, rss_feed_ids|
				yield rss_feed_ids
			end
		ensure
			unlisten
		end
		
		########
		private
		########
	
		def listen
			RssFeed.connection.execute "LISTEN rss_feeds_channel"
		end
	
		def unlisten
		  RssFeed.connection.execute "UNLISTEN rss_feeds_channel"
		end
	
		def notify_rss_feed_created(rss_feed_ids)
			RssFeed.connection.execute "NOTIFY rss_feeds_channel, '#{rss_feed_ids}'"
		end
	end
		
end

app/models/user.rb
class User < ActiveRecord::Base

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true
	has_secure_password
  validates :password, length: { minimum: 8 }, allow_nil: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
			
	helper_method :current_user, :logged_in?
	
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
  
	def logged_in?
		session[:user_id].present?
	end

	def authorize
		redirect_to '/login' unless current_user
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authorize, only: [:create]
	before_action :get_rss_feed
		
		
	def index
		@comments = @rss_feed.comments.includes(:replies)
		respond_to do |format|
			format.js 
		end
	end
	
	def create
		@comment = @rss_feed.comments.new(comment_params)
		@comment.parent_id = params[:comment_id]
		@comment.save
		respond_to do |format|
			format.js 
		end
	end
	
	########
	private
	########
	
	def comment_params
		params.require(:comment).permit(:body, :parent_id)
	end

	def get_rss_feed
		return redirect_to :back, notice: "Your comment wasn't posted!" unless params[:rss_feed_id]
		@rss_feed = RssFeed.find_by_id(params[:rss_feed_id]) 
	end
	
end

app/controllers/rss_feeds_controller.rb
class RssFeedsController < ApplicationController
	include ActionController::Live	 
	 
	def index
		@rss_feeds = RssFeed.order(published_at: :desc).limit(10).offset(get_offset(params[:page] ||= 1))
		respond_to do |format|
			format.html
			format.js 
		end
	end
	
	def recent
		@rss_feeds = RssFeed.find(params[:rss_feed_ids].split(','))
		respond_to do |format|
			format.js
		end
	end
	 
	def events
		# SSE expects the `text/event-stream` content type
		response.headers['Content-Type'] = 'text/event-stream'
		sse = SSE.new(response.stream, retry: 300, event: "refresh")
		begin
			RssFeed.notify_rss_feed_creation do |rss_feed_ids|
				sse.write({rss_feed_ids: rss_feed_ids})
			end
		rescue IOError
			# When the client disconnects, we'll get an IOError on write
		ensure
			sse.close
		end
	end
	
	########
	private
	########

	def get_offset(page)
		case page.to_i
		when 1 then 0
		when 2 then 10
		else
			page.to_i.pred * 10
		end
	end
 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to '/'
		else
			flash[:error] = "Email or password doesn't match."
			redirect_to '/login'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to '/login'
	end
		
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :get_user, only: [:edit, :update]
	
	# GET /users/new
	def new
		@user = User.new
	end

	# GET /users/1/edit
	def edit
	end
  
	# POST /users
	def create
		@user = User.new(user_params)
		return render :new unless @user.valid?
		@user.save
		session[:user_id] = @user.id
		redirect_to root_path, notice: 'User was successfully created.'
	end
	
	# PATCH/PUT /users/1
	def update
		if @user.update(user_params)
			redirect_to root_path, notice: 'User was successfully updated.'
		else
			render :edit 
		end
	end
		
	#############
	private
	#############
	
	def get_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pub_subs_helper.rb
module PubSubsHelper
end

app/helpers/rss_feeds_helper.rb
module RssFeedsHelper
	def format_date date
		date.strftime("%a, %d %b %Y %H:%M:%S")
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
%li
  .comment
    = comment.body
    %br
    %small= "#{time_ago_in_words(comment.created_at) } ago"
    -if logged_in? && comment.parent_id.nil?
      .box
        -if logged_in?   
          = form_for [comment.rss_feed, comment, Comment.new], remote: true, html: { id: "comment_#{comment.id}_reply" } do |f|
            = render "comments/form", f: f, placeholder: "Add a reply"
  %ul.mlt-50{id: "comment_#{comment.id}_replies"}
    =render comment.replies 

app/views/comments/_form.html.haml
.txt
  = f.text_area 'body', class: 'form-control', placeholder: placeholder
  .clear
  = f.submit 'Post', class: 'btn btn-primary mtp-5'

app/views/comments/create.js.haml
-if @comment.errors.any?
  alert("#{@comment.errors.full_messages.join('\n')}");
-else
  -if @comment.parent_id
    $("#comment_#{@comment.parent_id}_reply")[0].reset();
    $("#comment_#{@comment.parent_id}_replies").append("#{j(render @comment)}");
  -else
    $("#rss_feed_#{@rss_feed.id}_comment")[0].reset();
    $("#feed_#{@rss_feed.id}_comments").append("#{j(render @comment)}");

  $("#cmt_cnt_#{@rss_feed.id}").html("#{@rss_feed.comments_count} comments");

app/views/comments/index.js.haml
-if @comments.empty?
    $("#feed_#{@rss_feed.id}_comments").html("<p>Be the first to add comment.</p>");
-else
    $("#feed_#{@rss_feed.id}_comments").html("#{j(render @comments)}");

app/views/layouts/_flash_messages.html.haml
.mtp-50
  -if flash[:error]
    .alert.alert-danger{role: "alert"}
      = flash[:error]
  -if alert
    .alert.alert-success{role: "alert"}
    = notice
  = alert

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title FeedReader
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-fixed-top.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} Feed Reader
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            -if logged_in?
              %li
                = link_to current_user.name, edit_user_path(current_user)
              %li
                = link_to "Logout", '/logout'
            -else
              %li
                = link_to 'Login', '/login'
              %li
                = link_to 'Signup', '/signup'
    
    .container.mtp-50
      = render 'layouts/flash_messages' 
      = yield

app/views/rss_feeds/_rss_feed.html.haml
.col
  %h2= rss_feed.title
  %p= "Posted: #{format_date rss_feed.published_at}"
  %p
    = rss_feed.summary
    = link_to 'more', rss_feed.url, target: 'blank'
  .comment_box
    = link_to "#{rss_feed.comments.size} comments", rss_feed_comments_path(rss_feed), remote: true, id: "cmt_cnt_#{rss_feed.id}"
    -if logged_in?   
      = form_for [rss_feed, Comment.new], remote: true, html: { id: "rss_feed_#{rss_feed.id}_comment" } do |f|
        = render "comments/form", f: f, placeholder: "Write a comment.."  
         
    %ul.comments{id: "feed_#{rss_feed.id}_comments"}

app/views/rss_feeds/index.html.haml
%h1="NDTV Top Stories"
#rss_feeds.mtp-50
  = render @rss_feeds
-unless @rss_feeds.blank?
  %p.mtp-5.pagination_link= link_to 'Load Older feeds', root_path(page: params[:page].to_i.succ), remote: true, id: "load_more_link"

app/views/rss_feeds/index.js.haml
-if @rss_feeds.empty?
    $('#load_more_link').replaceWith("No older feed to show.");
-else
    $('#rss_feeds').append("#{j(render @rss_feeds)}");
    $('#load_more_link').replaceWith("#{j(link_to 'Load Older feeds', root_path(page: params[:page].to_i.succ), remote: true, id: 'load_more_link')}");

app/views/rss_feeds/recent.js.haml
$("#rss_feeds").prepend("#{j(render @rss_feeds)}");

app/views/shared/_error_messages.html.haml
- if obj.errors.any?
  #error_explanation
    %h2
      = pluralize(obj.errors.count, "error")
      ="prohibited this #{obj.class.to_s.downcase} from being saved:"
    %ul
      - obj.errors.full_messages.each do |message|
        %li= message

app/views/users/_form.html.haml
.form
  = form_for(@user) do |f|
    = render 'shared/error_messages', obj: @user
    .field
      = f.label :name
      %br
        = f.text_field :name, class: 'form-control'
    .field
      = f.label :email
      %br
        = f.email_field :email, class: 'form-control'
    .field
      = f.label :password
      %br
        = f.password_field :password, autocomplete: :off, class: 'form-control'
    .field
      = f.label :password_confirmation
      %br
        = f.password_field :password_confirmation, autocomplete: :off, class: 'form-control'
    .actions
      = f.submit 'Submit', class: 'btn btn-lg btn-primary btn-block'

app/views/users/edit.html.haml
%h1 Edit Profile
= render 'form'

app/views/users/new.html.haml
%h1 Signup!
= render 'form'